// Copyright Epic Games, Inc. All Rights Reserved.

#include "BlueprintTool/K2Nodes/ExK2Node_AsyncBase.h"

#include "BlueprintTool/Slate/SGraphNode_ExAsyncDebug.h"
#include "ObjectTools.h"
#include "K2Node_CallFunction.h"
#include "K2Node_IfThenElse.h"
#include "K2Node_TemporaryVariable.h"
#include "KismetCompiler.h"
#include "Kismet/KismetStringLibrary.h"
#include "Kismet/KismetSystemLibrary.h"
#include "Kismet2/BlueprintEditorUtils.h"

#define LOCTEXT_NAMESPACE "UExK2Node_AsyncBase"

UExK2Node_AsyncBase::UExK2Node_AsyncBase(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
}

FText UExK2Node_AsyncBase::GetTooltipText() const
{
	const UFunction* FactoryFunction = nullptr;
	if (ProxyFactoryClass && ProxyFactoryFunctionName != NAME_None)
	{
		FactoryFunction = ProxyFactoryClass->FindFunctionByName(ProxyFactoryFunctionName);
	}

	if (FactoryFunction)
	{
		return FText::FromString(ObjectTools::GetDefaultTooltipForFunction(FactoryFunction, true));
	}

	return GetNodeTitle(ENodeTitleType::ListView);
}

TSharedPtr<SGraphNode> UExK2Node_AsyncBase::CreateVisualWidget()
{
	return SNew(SGraphNode_ExAsyncDebug, this);
}

void UExK2Node_AsyncBase::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent)
{
	Super::PostEditChangeProperty(PropertyChangedEvent);
}

void UExK2Node_AsyncBase::SetNodeInfoPinValue(const UEdGraphSchema_K2* Schema, UEdGraphPin* NodeInfoVarPin)
{
	GenerateContextUniqueId();
	const auto Property = GetClass()->FindPropertyByName(GET_MEMBER_NAME_STRING_CHECKED(UExK2Node_AsyncBase, NodeInfo));
	Schema->ConvertPropertyToPinType(Property, /*out*/ NodeInfoVarPin->PinType);
	FString DefaultValueAsString;
	const bool bDefaultValueSet = FBlueprintEditorUtils::PropertyValueToString(Property,
		reinterpret_cast<const uint8*>(this), DefaultValueAsString, this);
	check(bDefaultValueSet);
	Schema->SetPinAutogeneratedDefaultValue(NodeInfoVarPin, DefaultValueAsString);
}

void UExK2Node_AsyncBase::GenerateContextUniqueId()
{
	NodeInfo.UUID = GetNodeUUID();
	NodeInfo.GraphNodeGuid = NodeGuid.ToString(EGuidFormats::DigitsWithHyphens);
	if (const auto RealOwner = GetOuter()->GetOuter())
	{
		if (NodeInfo.UniqueId.IsEmpty())
		{
			const auto UniId = RealOwner->GetUniqueID();
			NodeInfo.UniqueId = FString::Format(TEXT("{0}_{1}"), { FStringFormatArg(NodeInfo.UUID), FStringFormatArg(UniId) });
		}
	}
	else
	{
		UE_LOG(LogBlueprintNodeGraph, Error, TEXT("[UExK2Node_AsyncBase::GenerateContextUniqueId] - Owner is Not Actor, %s"), RealOwner ? *RealOwner->GetName() : TEXT(""));
	}
}

void UExK2Node_AsyncBase::SetUUIDAndNodeInfo(const UEdGraphSchema_K2* Schema)
{
	// uuid
	UEdGraphPin* UUIDPin = FindPin(ExLatentTaskHelper::UUIDPinName);
	if (UUIDPin)
	{
		UUIDPin->DefaultValue = GetNodeUUID();
	}
	// input count pin
	UEdGraphPin* InputCountPin = FindPin(ExLatentTaskHelper::InputCountPinName);
	if (InputCountPin)
	{
		const int32 ExecCount = GetInputBranchCount();
		InputCountPin->DefaultValue = UKismetStringLibrary::Conv_IntToString(ExecCount);
	}
	// set node info
	UEdGraphPin* NodeInfoPin = FindPin(ExLatentTaskHelper::K2NodeInfoPinName);
	if (NodeInfoPin)
	{
		SetNodeInfoPinValue(Schema, NodeInfoPin);
	}
}

void UExK2Node_AsyncBase::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	check(SourceGraph && Schema);
	
	// SetValue: UUID && InputCount
	SetUUIDAndNodeInfo(Schema);
	
	UK2Node::ExpandNode(CompilerContext, SourceGraph);
	
	bool bIsErrorFree = true;
	
	// ------------------------------------------------------------------------------------------
	// CREATE A CALL TO FACTORY THE PROXY OBJECT
	// ------------------------------------------------------------------------------------------
	UK2Node_CallFunction* const CallCreateProxyObjectNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallCreateProxyObjectNode->FunctionReference.SetExternalMember(ProxyFactoryFunctionName, ProxyFactoryClass);
	CallCreateProxyObjectNode->AllocateDefaultPins();
	bIsErrorFree &= CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Execute), *CallCreateProxyObjectNode->FindPinChecked(UEdGraphSchema_K2::PN_Execute)).CanSafeConnect();
	for (UEdGraphPin* CurrentPin : Pins)
	{
		if (FBaseAsyncTaskHelper::ValidDataPin(CurrentPin, EGPD_Input))
		{
			UEdGraphPin* DestPin = CallCreateProxyObjectNode->FindPin(CurrentPin->PinName); // match function inputs, to pass data to function from CallFunction node

			// NEW: if no DestPin, assume it is a Class Spawn PRoperty - not an error
			if (DestPin)
			{
				bIsErrorFree &= CompilerContext.CopyPinLinksToIntermediate(*CurrentPin, *DestPin).CanSafeConnect();
			}
		}
	}

	UEdGraphPin* const ProxyObjectPin = CallCreateProxyObjectNode->GetReturnValuePin();
	check(ProxyObjectPin);
	UEdGraphPin* OutputAsyncTaskProxy = FindPin(FBaseAsyncTaskHelper::GetAsyncTaskProxyName());
	if (OutputAsyncTaskProxy)
	{
		bIsErrorFree &= CompilerContext.MovePinLinksToIntermediate(*OutputAsyncTaskProxy, *ProxyObjectPin).CanSafeConnect();
	}
	
	// ------------------------------------------------------------------------------------------
	// GATHER OUTPUT PARAMETERS AND PAIR THEM WITH LOCAL VARIABLES
	// ------------------------------------------------------------------------------------------
	TArray<FBaseAsyncTaskHelper::FOutputPinAndLocalVariable> VariableOutputs;
	for (UEdGraphPin* CurrentPin : Pins)
	{
		if ((OutputAsyncTaskProxy != CurrentPin) && FBaseAsyncTaskHelper::ValidDataPin(CurrentPin, EGPD_Output))
		{
			const FEdGraphPinType& PinType = CurrentPin->PinType;
			UK2Node_TemporaryVariable* TempVarOutput = CompilerContext.SpawnInternalVariable(
				this, PinType.PinCategory, PinType.PinSubCategory, PinType.PinSubCategoryObject.Get(), PinType.ContainerType, PinType.PinValueType);
			bIsErrorFree &= TempVarOutput->GetVariablePin() && CompilerContext.MovePinLinksToIntermediate(*CurrentPin, *TempVarOutput->GetVariablePin()).CanSafeConnect();
			VariableOutputs.Add(FBaseAsyncTaskHelper::FOutputPinAndLocalVariable(CurrentPin, TempVarOutput));
		}
	}

	// first set Then Pin
	UEdGraphPin* LastThenPin = CallCreateProxyObjectNode->FindPinChecked(UEdGraphSchema_K2::PN_Then);

	// ------------------------------------------------------------------------------------------
	// FOR EACH DELEGATE DEFINE EVENT, CONNECT IT TO DELEGATE AND IMPLEMENT A CHAIN OF ASSIGMENTS
	// ------------------------------------------------------------------------------------------
	UK2Node_IfThenElse* ValidateProxyNode;
	{
		CompilerHandleDelegates(CompilerContext, SourceGraph, ValidateProxyNode, CallCreateProxyObjectNode, ProxyObjectPin, VariableOutputs, LastThenPin, bIsErrorFree);
	}
	
	// --------------------------------------------------------------------------------------
	// Create call function "SetK2NodeInfo" to set info to proxy object if necessary
	// --------------------------------------------------------------------------------------
	UK2Node_IfThenElse* ProxySetK2NodeInfoValidateNode = nullptr;
	if (ProxySetK2NodeInfoFunctionName != NAME_None)
	{
		CompilerSetK2NodeInfoCall(CompilerContext, SourceGraph, ProxySetK2NodeInfoValidateNode, ProxyObjectPin, LastThenPin, bIsErrorFree);
	}

	// --------------------------------------------------------------------------------------
	// Create a call to activate the proxy object if necessary
	// --------------------------------------------------------------------------------------
	UK2Node_IfThenElse* ProxyActivateValidateProxyNode = nullptr;
	if (ProxyActivateFunctionName != NAME_None)
	{
		CompilerSetActiveCall(CompilerContext, SourceGraph, ProxyActivateValidateProxyNode, ProxyObjectPin, LastThenPin, bIsErrorFree);
	}

	// --------------------------------------------------------------------------------------
	// 主 Then：接到 Activate 链末端（原默认行为；无子类覆盖，不保留虚函数钩子）
	// --------------------------------------------------------------------------------------
	UEdGraphPin* OriginalThenPin = FindPin(UEdGraphSchema_K2::PN_Then);
	if (OriginalThenPin && LastThenPin)
	{
		bIsErrorFree &= CompilerContext.MovePinLinksToIntermediate(*OriginalThenPin, *LastThenPin).CanSafeConnect();
	}
	if (ValidateProxyNode)
	{
		bIsErrorFree &= CompilerContext.CopyPinLinksToIntermediate(*LastThenPin, *ValidateProxyNode->GetElsePin()).CanSafeConnect();
	}
	if (ProxySetK2NodeInfoValidateNode)
	{
		bIsErrorFree &= CompilerContext.CopyPinLinksToIntermediate(*LastThenPin, *ProxySetK2NodeInfoValidateNode->GetElsePin()).CanSafeConnect();
	}
	if (ProxyActivateValidateProxyNode)
	{
		bIsErrorFree &= CompilerContext.CopyPinLinksToIntermediate(*LastThenPin, *ProxyActivateValidateProxyNode->GetElsePin()).CanSafeConnect();
	}
	
	if (!bIsErrorFree)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("InternalConnectionError", "BaseAsyncTask: Internal connection error. @@").ToString(), this);
	}

	// Make sure we caught everything
	BreakAllNodeLinks();
}

// --------------------------------------------------------------------------------------
// Create call function "SetK2NodeInfo" to set info to proxy object if necessary
// --------------------------------------------------------------------------------------
void UExK2Node_AsyncBase::CompilerSetK2NodeInfoCall(class FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, class UK2Node_IfThenElse*& OutProxyValidateNode,
		UEdGraphPin* const ProxyObjectPin, UEdGraphPin*& OutLastThenPin, bool& bIsErrorFree)
{
	if (ProxySetK2NodeInfoFunctionName == NAME_None)
		return;
	
	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	
	// Validate the proxy object is still valid, in which case we don't need to call the Proxy.		
	UK2Node_CallFunction* ProxySetK2NodeInfoIsValidFuncNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	const FName IsValidFuncName = GET_FUNCTION_NAME_CHECKED(UKismetSystemLibrary, IsValid);
	ProxySetK2NodeInfoIsValidFuncNode->FunctionReference.SetExternalMember(IsValidFuncName, UKismetSystemLibrary::StaticClass());
	ProxySetK2NodeInfoIsValidFuncNode->AllocateDefaultPins();
	UEdGraphPin* ProxySetNodeInfoIsValidInputPin = ProxySetK2NodeInfoIsValidFuncNode->FindPinChecked(ExLatentTaskHelper::ObjectPinName);

	// connect check input param if is-valid
	bIsErrorFree &= Schema->TryCreateConnection(ProxyObjectPin, ProxySetNodeInfoIsValidInputPin);

	UK2Node_IfThenElse* ProxySetK2NodeInfoValidateProxyNode = CompilerContext.SpawnIntermediateNode<UK2Node_IfThenElse>(this, SourceGraph);
	ProxySetK2NodeInfoValidateProxyNode->AllocateDefaultPins();
	bIsErrorFree &= Schema->TryCreateConnection(ProxySetK2NodeInfoIsValidFuncNode->GetReturnValuePin(), ProxySetK2NodeInfoValidateProxyNode->GetConditionPin());
	OutProxyValidateNode = ProxySetK2NodeInfoValidateProxyNode;
	
	// connect exec pin
	bIsErrorFree &= Schema->TryCreateConnection(OutLastThenPin, ProxySetK2NodeInfoValidateProxyNode->GetExecPin());
	OutLastThenPin = ProxySetK2NodeInfoValidateProxyNode->GetThenPin();
	
	// -------------------------- Actually call the SetK2NodeInfo function --------------------------
	
	UK2Node_CallFunction* const CallSetK2NodeInfoProxyNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallSetK2NodeInfoProxyNode->FunctionReference.SetExternalMember(ProxySetK2NodeInfoFunctionName, ProxyClass);
	CallSetK2NodeInfoProxyNode->AllocateDefaultPins();
	
	// Hook up the self connection
	UEdGraphPin* SetK2NodeInfoCallSelfPin = Schema->FindSelfPin(*CallSetK2NodeInfoProxyNode, EGPD_Input);
	check(SetK2NodeInfoCallSelfPin);
	bIsErrorFree &= Schema->TryCreateConnection(ProxyObjectPin, SetK2NodeInfoCallSelfPin);
	UEdGraphPin* CallSetK2NodeInfoFunctionVarPin = CallSetK2NodeInfoProxyNode->FindPinChecked(ExLatentTaskHelper::K2NodeInfoPinName);
	check(CallSetK2NodeInfoFunctionVarPin);
	{
		// ----------- Node Info Param Pin -----------
		UEdGraphPin* NodeInfoVarPin = CreatePin(EGPD_Output, NAME_None, ExLatentTaskHelper::K2NodeInfoPinName);
		check(NodeInfoVarPin);
		if (Schema->PinDefaultValueIsEditable(*NodeInfoVarPin))
		{
			SetNodeInfoPinValue(Schema, NodeInfoVarPin);
			// temp param link to function param pin
			bIsErrorFree &= CompilerContext.MovePinLinksToIntermediate(*NodeInfoVarPin, *CallSetK2NodeInfoFunctionVarPin).CanSafeConnect();
		}
		// ----------- Node Info Param Pin -----------
	}
	
	// -------------------------- Actually call the SetK2NodeInfo function --------------------------
	

	// Hook the activate node up in the exec chain
	UEdGraphPin* ActivateExecPin = CallSetK2NodeInfoProxyNode->FindPinChecked(UEdGraphSchema_K2::PN_Execute);
	UEdGraphPin* ActivateThenPin = CallSetK2NodeInfoProxyNode->FindPinChecked(UEdGraphSchema_K2::PN_Then);

	bIsErrorFree &= Schema->TryCreateConnection(OutLastThenPin, ActivateExecPin);

	// current exec set to after this Function Exec
	OutLastThenPin = ActivateThenPin;
}

// --------------------------------------------------------------------------------------
// Create call function "Active" to set info to proxy object if necessary
// --------------------------------------------------------------------------------------
void UExK2Node_AsyncBase::CompilerSetActiveCall(class FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, class UK2Node_IfThenElse*& OutProxyValidateNode,
		UEdGraphPin* const ProxyObjectPin, UEdGraphPin*& OutLastThenPin, bool& bIsErrorFree)
{
	if (ProxyActivateFunctionName == NAME_None)
		return;
	
	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	
	// Validate the proxy object is still valid, in which case we don't need to call the ProxyActivateFunction.		
	UK2Node_CallFunction* ProxyActivateIsValidFuncNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	const FName IsValidFuncName = GET_FUNCTION_NAME_CHECKED(UKismetSystemLibrary, IsValid);
	ProxyActivateIsValidFuncNode->FunctionReference.SetExternalMember(IsValidFuncName, UKismetSystemLibrary::StaticClass());
	ProxyActivateIsValidFuncNode->AllocateDefaultPins();
	UEdGraphPin* ProxyActivateIsValidInputPin = ProxyActivateIsValidFuncNode->FindPinChecked(ExLatentTaskHelper::ObjectPinName);

	bIsErrorFree &= Schema->TryCreateConnection(ProxyObjectPin, ProxyActivateIsValidInputPin);

	UK2Node_IfThenElse* ProxyActivateValidateProxyNode = CompilerContext.SpawnIntermediateNode<UK2Node_IfThenElse>(this, SourceGraph);
	ProxyActivateValidateProxyNode->AllocateDefaultPins();
	bIsErrorFree &= Schema->TryCreateConnection(ProxyActivateIsValidFuncNode->GetReturnValuePin(), ProxyActivateValidateProxyNode->GetConditionPin());
	OutProxyValidateNode = ProxyActivateValidateProxyNode;

	bIsErrorFree &= Schema->TryCreateConnection(OutLastThenPin, ProxyActivateValidateProxyNode->GetExecPin());
	OutLastThenPin = ProxyActivateValidateProxyNode->GetThenPin();

	// -------------------------- Actually call the Activate function --------------------------
	UK2Node_CallFunction* const CallActivateProxyObjectNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallActivateProxyObjectNode->FunctionReference.SetExternalMember(ProxyActivateFunctionName, ProxyClass);
	CallActivateProxyObjectNode->AllocateDefaultPins();
	// Hook up the self connection
	UEdGraphPin* ActivateCallSelfPin = Schema->FindSelfPin(*CallActivateProxyObjectNode, EGPD_Input);
	check(ActivateCallSelfPin);
	bIsErrorFree &= Schema->TryCreateConnection(ProxyObjectPin, ActivateCallSelfPin);
	// -------------------------- Actually call the Activate function --------------------------

	// Hook the activate node up in the exec chain
	UEdGraphPin* ActivateExecPin = CallActivateProxyObjectNode->FindPinChecked(UEdGraphSchema_K2::PN_Execute);
	UEdGraphPin* ActivateThenPin = CallActivateProxyObjectNode->FindPinChecked(UEdGraphSchema_K2::PN_Then);

	bIsErrorFree &= Schema->TryCreateConnection(OutLastThenPin, ActivateExecPin);

	OutLastThenPin = ActivateThenPin;
}

void UExK2Node_AsyncBase::CompilerHandleDelegates(class FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph, class UK2Node_IfThenElse*& OutProxyValidateNode,
		const class UK2Node_CallFunction* InCallCreateProxyObjectNode, UEdGraphPin* const ProxyObjectPin,
		const TArray<FBaseAsyncTaskHelper::FOutputPinAndLocalVariable>& VariableOutputs, UEdGraphPin*& OutLastThenPin, bool& bIsErrorFree)
{
	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	
	UK2Node_CallFunction* IsValidFuncNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	const FName IsValidFuncName = GET_FUNCTION_NAME_CHECKED(UKismetSystemLibrary, IsValid);
	IsValidFuncNode->FunctionReference.SetExternalMember(IsValidFuncName, UKismetSystemLibrary::StaticClass());
	IsValidFuncNode->AllocateDefaultPins();
	UEdGraphPin* IsValidInputPin = IsValidFuncNode->FindPinChecked(ExLatentTaskHelper::ObjectPinName);

	bIsErrorFree &= Schema->TryCreateConnection(ProxyObjectPin, IsValidInputPin);

	UK2Node_IfThenElse* ValidateProxyNode = CompilerContext.SpawnIntermediateNode<UK2Node_IfThenElse>(this, SourceGraph);
	ValidateProxyNode->AllocateDefaultPins();
	bIsErrorFree &= Schema->TryCreateConnection(IsValidFuncNode->GetReturnValuePin(), ValidateProxyNode->GetConditionPin());
	OutProxyValidateNode = ValidateProxyNode;

	bIsErrorFree &= Schema->TryCreateConnection(OutLastThenPin, ValidateProxyNode->GetExecPin());
	OutLastThenPin = ValidateProxyNode->GetThenPin();

	// handle delegates
	bIsErrorFree &= HandleDelegates(VariableOutputs, ProxyObjectPin, OutLastThenPin, SourceGraph, CompilerContext);

	if (InCallCreateProxyObjectNode->FindPinChecked(UEdGraphSchema_K2::PN_Then) == OutLastThenPin)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingDelegateProperties", "UExK2Node_AsyncBase: Proxy has no delegates defined. @@").ToString(), this);
	}
}

#undef LOCTEXT_NAMESPACE
